name: Content and IA Centralized Team Product Support Request Form
description: Use this ticket to request support from the centralized content and information architecture team.
title: "[INTAKE] Team Name: Initiative Name"
body:
  - type: markdown
    attributes:
      value: |
        # Content and IA Product Support Request
  - type: markdown
    attributes:
      value: |
        Use this ticket to request collaboration on a new initiative with the sitewide Content ane Information Architecture shared services team.
        
        **Please note:** If you're requesting a page/URL redirect, a URL change, or a vanity URL, [please open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?template=redirect-request.md) instead.
  - type: markdown
    attributes:
      value: |
        "## Team info"
  - type: input
    attributes:
      label: Product name
    validations:
      required: true
  - type: input
    attributes:
      label: Team name
    validations:
      required: true
  - type: input
    attributes:
      label: Slack channel
    validations:
      required: true
  - type: input
    attributes:
      label: OCTO product owner
    validations:
      required: true
  - type: input
    attributes:
      label: Product manager
    validations:
      required: true
  - type: input
    attributes:
      label: Designer(s)
    validations:
      required: true
  - type: input
    attributes:
      label: Dedicated content writer on your team (if you have one)
    validations:
      required: false


  - type: markdown
    attributes:
      value: |
        "***
        ## About your initiative"
  - type: checkboxes
    attributes:
      label: What audiences is your work for
      options:
        - label: Veterans and/or their family members or caregivers
        - label: Internal designers and product team members (i.e. pattern or standards work)
        - label: Other VA.gov audience (describe the audience below)
      validations:
        required: true
  - type: input
    attributes:
      label: Describe the other VA.gov audience
      validations:
        required: false
  - type: checkboxes
    attributes:
      label: Which of these descriptions best fits the work we’ll partner on?
      options:
        - label: Veterans and/or their family members or caregivers
        - label: Internal designers and product team members (i.e. pattern or standards work)
        - label: Other VA.gov audience (describe the audience below)
        - label: Digitizing a new form
        - label: Creating a new digital tool for Veterans or their beneficiaries
        - label: Updating an existing form or tool
        - label: Translating a form or tool into Spanish
        - label: Adding new unauthenticated content to VA.gov
        - label: Updating existing unauthenticated content on VA.gov
        - label: Components, patterns, or general standards
        - label: Something else (describe below)
      validations:
        required: true
    - type: input
      attributes:
        label: Describe the "something else"
      validations:
        required: false


  
  - type: markdown
      attributes:
        value: |
          "### Supporting artifacts"
  
          _Add links to all applicable artifacts and issues._
   - type: input
    id: Product outline
    attributes:
      label: Product outline
    validations:
      required: true
   - type: input
    id: Collaboration Cycle ticket
    attributes:
      label: Collaboration Cycle ticket
    validations:
      required: true
   - type: input
    id: Content source of truth doc
    attributes:
      label: Content source of truth doc
    validations:
      required: false
   - type: input
    id: Figma file
    attributes:
      label: Figma file
    validations:
      required: true
   - type: input
    id: Mural
    attributes:
      label: Mural
    validations:
      required: false
  
  - type: markdown
      attributes:
        value: |
          ### Timeline
  
         _Provide information about your expected/planned timeline._
   - type: input
    id: Estimated launch
    attributes:
      label: Estimated launch
    validations:
      required: true
   - type: input
    id: Where are you at in your design/development process?
    attributes:
      label: Where are you at in your design/development process?
    validations:
      required: true
  
   - type: input
    id: If a staged launch is planned, provide details.
    attributes:
      label: If a staged launch is planned, provide details.
    validations:
      required: false
