name: Content and IA Centralized Team Product Support Request Form
description: Use this ticket to request support from the centralized content and information
  architecture team.
title: "[INTAKE] Team Name: Initiative Name"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      # Content and IA Product Support Request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) shared services team. Feel free to delete instructions and unselected options from the ticket to make it easier to scan.
<br>

**Please note:** If you're requesting a page/URL redirect, a URL change, or a vanity URL, [please open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?template=redirect-request.md) instead.


## Team info
_Tell us about your team._
- **Product name:**
- **Team name:**
- **Slack channel:**
- **OCTO product owner:** 
- **Product manager:** 
- **Designer(s):**
- **Dedicated content writer on your team (if you have one):** 

 
## About your initiative

### What audiences is your work for
- [ ] Veterans and/or their family members or caregivers
- [ ] Other VA.gov audience
  - Please describe the audience:
- [ ] Internal designers and product team members (i.e. pattern or standards work)

### Which of these descriptions best fits the work we’ll partner on?
_Select all that apply._

- [ ] Digitizing a new form
- [ ] Creating a new digital tool for Veterans or their beneficiaries
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Components, patterns, or general standards
- [ ] Something else:

### Describe the work effort
_Provide a brief description of the work_


### Supporting artifacts
_Add links to all applicable artifacts and issues._
- Product outline
- Collaboration Cycle ticket #
- Content source of truth doc
- Figma file
- Mural
  
### Timeline
_Provide information about your expected/planned timeline._
- **Estimated launch timeline:**
- **Where are you at in your design/development process?**
- **Is a staged launch planned? If so, please provide details.**
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
