---
name: Content and IA Product Support Task version 3
title: "[TASK:] Task name"
labels: content-ia-centralized-team
body:
- type: input
  id: prevalence
  attributes:
    label: Bug prevalence
    description: How often do you or others encounter this bug?
    placeholder: Whenever I visit the user account page (1-2 times a week)
  validations:
    required: true

---

### Overview

#### Task description
_What details are necessary for understanding the specific work or request tracked by this issue?_

#### Parent epic/work effort

- [Name and issue # of parent epic]()

#### Relevant links and artifacts

- [Link or artifact]()
- [Link or artifact]()
- [Link or artifact]()

#### Timeline
_When does this task need to be completed by?_


### Acceptance Criteria
- [ ] Criteria 1...
